name: Check for updates

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cloned repository
        uses: actions/checkout@v2

      - name: Add original repository as upstream
        run: |
          git remote add upstream https://github.com/EricZimmerman/KapeFiles || true

      - name: Fetch updates from upstream
        run: git fetch upstream || true

      - name: Check for updates
        id: check_updates
        run: |
          set -e
          UPSTREAM_BRANCH=$(git branch -r | grep 'upstream/main' || true)
          if [ -n "$UPSTREAM_BRANCH" ]; then
            UPDATES=$(git log HEAD..upstream/main --oneline || true)
            if [ -n "$UPDATES" ]; then
              echo "updates=$UPDATES" >> $GITHUB_ENV
            fi
          else
            echo "updates=" >> $GITHUB_ENV
          fi

      - name: Write updates to log
        if: env(updates)
        run: |
          echo "Date: $(date +'%Y-%m-%d')" >> updates_log.txt
          echo "Repository: ${{ github.repository }}" >> updates_log.txt
          echo "Updates:" >> updates_log.txt
          echo "${{ env.updates }}" >> updates_log.txt
          echo "---" >> updates_log.txt

      - name: Commit and push changes
        if: env(updates)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add updates_log.txt
          git commit -m 'Update log with new updates'
          git push origin main
