name: Check for updates

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cloned repository
        uses: actions/checkout@v2

      - name: Get current branch
        id: get_branch
        run: echo "current_branch=$(git symbolic-ref --short HEAD)" >> $GITHUB_ENV

      - name: Add original repository as upstream
        run: git remote add upstream https://github.com/EricZimmerman/KapeFiles || true

      - name: Fetch updates from upstream
        run: git fetch upstream

      - name: Check for upstream/main branch
        id: check_branch
        run: |
          UPSTREAM_BRANCH=$(git branch -r | grep 'upstream/main' || echo '')
          echo "branch_exists=$UPSTREAM_BRANCH" >> $GITHUB_ENV

      - name: Check for updates
        id: check_updates
        run: |
          if [ -n "${{ env.branch_exists }}" ]; then
            UPDATES=$(git log HEAD..upstream/main --oneline || echo '')
            echo "updates=$UPDATES" >> $GITHUB_ENV
          else
            echo "updates=" >> $GITHUB_ENV

      - name: Write updates to log
        run: |
          echo "Date: $(date +'%Y-%m-%d')" >> updates_log.txt
          echo "Repository: ${{ github.repository }}" >> updates_log.txt
          if [ -n "${{ env.branch_exists }}" ]; then
            if [ -n "${{ env.updates }}" ]; then
              echo "Updates:" >> updates_log.txt
              echo "${{ env.updates }}" >> updates_log.txt
            else
              echo "No new updates found." >> updates_log.txt
            fi
          else
            echo "Upstream branch 'main' does not exist." >> updates_log.txt
          fi
          echo "---" >> updates_log.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add updates_log.txt
          git commit -m 'Update log with new updates'
          git push origin HEAD:${{ env.current_branch }}
